### PR TITLE
adding PySDM output file + first PySDM plots in plot_CliMa.ipynb

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by slayoo** [comment]
image

**Comment by slayoo** [comment]
- changed ``t_idx`` from ``0`` to ``-1`` (as PySDM starts with no liquid water)
- redefined ``rho_d`` from ``(rho - p / Rd / T / (1/q_vap + 1/eps - 1.)) / q_dry`` to ``rho*q_dry``

**Review by trontrytel — APPROVED** [review]

**Comment by slayoo** [comment]
We should still solve this:

image

**Comment by trontrytel** [comment]
On the branch `aj/testing` I added a function that computes the pressure the way it is done in the Machine.jl. All the constants are exposed too. Let me know if you see anything wrong with it.

**Comment by slayoo** [comment]
With 
image, the pressure profiles match very well: image

So it's apparently not related to constants or initial pressure profile. It is likely that we treat differently the way the change in vapour (and liquid?) mixing ratio affects the calculated pressure.

**Comment by trontrytel** [comment]
`p = p_1000 * ((p_0 / p_1000)**(_R_d / _cp_d) - _R_d / _cp_d * _grav / θ_0 / R_m * (z - z_0))**(_cp_d / _R_d)`

I do use, for some reason that I can't remember now, `R_m` in one place in the pressure equation. I guess I was trying to get the total pressure corresponding to the total density.

**Pull request merged**
