### PR TITLE
run PySDM's ICMW example from Julia using PyCall

### PR DESCRIPTION
**Pull request by slayoo**

### CODE REVIEW

**Comment by slayoo** [comment]
works on Linux and Windows, on OSX there's a cryptic error apparently unrelated to our code:
```
   Building PyCall → `~/.julia/packages/PyCall/BcTLp/deps/build.log`
Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file /Users/ci/miniconda3/conda-bld/llvmdev_1596534261649/work/include/llvm/Support/CommandLine.h, line 853.

signal (6): Abort trap: 6
in expression starting at none:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 3436780 (Pool: 3435856; Big: 924); GC: 4
/Users/runner/work/_temp/f03476f8-48c8-40a4-8849-6e632ffc94f1.sh: line 3:  1489 Abort trap: 6
```

@trontrytel - could you please try it on your OSX machine?

**Comment by trontrytel** [comment]
> works on Linux and Windows, on OSX there's a cryptic error apparently unrelated to our code:
> 
> ```
>    Building PyCall → `~/.julia/packages/PyCall/BcTLp/deps/build.log`
> Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file /Users/ci/miniconda3/conda-bld/llvmdev_1596534261649/work/include/llvm/Support/CommandLine.h, line 853.
> 
> signal (6): Abort trap: 6
> in expression starting at none:1
> __pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
> Allocations: 3436780 (Pool: 3435856; Big: 924); GC: 4
> /Users/runner/work/_temp/f03476f8-48c8-40a4-8849-6e632ffc94f1.sh: line 3:  1489 Abort trap: 6
> ```
> 
> @trontrytel - could you please try it on your OSX machine?

So far I'm getting this:

```
ERROR: PyError (PyImport_ImportModule

The Python package PySDM_examples.ICMW_2012_case_1.example could not be imported by pyimport. Usually this means
that you did not install PySDM_examples.ICMW_2012_case_1.example in the Python version being used by PyCall.

PyCall is currently configured to use the Julia-specific Python distribution
installed by the Conda.jl package.  To install the PySDM_examples.ICMW_2012_case_1.example module, you can
use `pyimport_conda("PySDM_examples.ICMW_2012_case_1.example", PKG)`, where PKG is the Anaconda
package the contains the module PySDM_examples.ICMW_2012_case_1.example, or alternatively you can use the
Conda package directly (via `using Conda` followed by `Conda.add` etcetera).

Alternatively, if you want to use a different Python distribution on your
system, such as a system-wide Python (as opposed to the Julia-specific Python),
you can re-configure PyCall with that Python.   As explained in the PyCall
documentation, set ENV["PYTHON"] to the path/name of the python executable
you want to use, run Pkg.build("PyCall"), and re-launch Julia.

) <class 'ModuleNotFoundError'>
ModuleNotFoundError("No module named 'PySDM_examples'")
```

**Comment by slayoo** [comment]
This helped with the same error on Github Actions:
``
pushfirst!(PyVector(pyimport("sys")."path"), ""); 
``

**Comment by trontrytel** [comment]
> This helped with the same error on Github Actions:
> `pushfirst!(PyVector(pyimport("sys")."path"), ""); `

Thanks! Must have copied something wrong before.

Now things work. And by this I mean that I get the same error on osx as the one you mentioned:
```

Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file /Users/ci/miniconda3/conda-bld/llvmdev_1596534261649/work/include/llvm/Support/CommandLine.h, line 853.

signal (6): Abort trap: 6
in expression starting at none:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 2548977 (Pool: 2548414; Big: 563); GC: 3
Abort trap: 6

```
I'll look into this

**Comment by slayoo** [comment]
People reported similar symptoms repeatedly for various projects, but I must say browsing through the issues listed below doesn't give me any clue what to do:
- https://github.com/rust-lang/rust/issues/18671
- https://bugs.gentoo.org/show_bug.cgi?id=697490
- https://github.com/gtcasl/gpuocelot/issues/85
- https://xamarin.github.io/bugzilla-archives/57/57742/bug.html
- https://support.codeplay.com/t/trouble-running-computecpp-samples-on-manjaro-linux/336/3
- https://bbs.archlinux.org/viewtopic.php?id=158824
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204699
(the last one is "MARKED AS SPAM"!)

Updating Xcode does not help on Gihub Actions runs... but I'm not sure if the updated LLVM was actually used by PyCall...

**Comment by trontrytel** [comment]
I have updated Xcode on my laptop but it does not help either. 

I have no idea how to solve this error. Should we focus in Linux/Windows builds and move on for now?

**Pull request merged**
